export const ONBOARDINGDATA = [
  {
    id: '1',
    title: '사전 자격 조건을 확인할게요',
    description: '앱에 오신 것을 환영합니다. 앱 사용 시작하기.회원가입.첫번째 가이드 확인하기',
    image: require('../assets/onboarding/onboarding1.png'),
  },
  {
    id: '2',
    title: '회원 정보 입력',
    description: '회원정보를 입력하면.더 다양한 기능을.사용하실 수 있습니다',
    image: require('../assets/onboarding/onboarding2.png'),
  },
  {
    id: '3',
    title: '구직자 명부 등록(EPS 등록)을 진행해주세요',
    description: '',
    image: require('../assets/onboarding/onboarding3.png'),
  },
  {
    id: '4',
    title: 'EPS-TOPIK 시험을 응시하세요',
    description: '',
    image: require('../assets/onboarding/onboarding4.png'),
  },
  {
    id: '5',
    title: 'EPS 구직자 명부탑재여부를 확인하세요',
    description: '',
    image: require('../assets/onboarding/onboarding5.png'),
  },
  {
    id: '6',
    title: '고용 매칭 및 근로계약을 진행하세요',
    description: '',
    image: require('../assets/onboarding/onboarding6.png'),
  },
  {
    id: '7',
    title: '사증 발급 인증서를 수령하세요',
    description: '',
    image: require('../assets/onboarding/onboarding7.png'),
  },
  {
    id: '8',
    title: '비자를 신청하세요',
    description: '',
    image: require('../assets/onboarding/onboarding8.png'),
  },
  {
    id: '9',
    title: '항공편을 예약하세요',
    description: '',
    image: require('../assets/onboarding/onboarding9.png'),
  },
  {
    id: '10',
    title: '관련서류를 잘 챙기고 출국하세요',
    description: '',
    image: require('../assets/onboarding/onboarding10.png'),
  },
  {
    id: '11',
    title: '한국 입국 15일 이내에 취업교육과 건강검진을 받으세요',
    description: '',
    image: require('../assets/onboarding/onboarding11.png'),
  },
  {
    id: '12',
    title: '사업장 배치 및 근로시작',
    description: '',
    image: require('../assets/onboarding/onboarding12.png'),
  },
  {
    id: '13',
    title: '외국인 등록증 발급하기',
    description: '',
    image: require('../assets/onboarding/onboarding12.png'),
  },
];